myblog/NLP/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'NLP'
urlpatterns = [
    path('',views.index,name='index'),
    path('Tutorial/',views.Tutorial,name='Tutorial'),
]

myblog/P/urls.py
from django.urls import path

from . import views

app_name = 'P'
urlpatterns = [
    path('HelloWorld/', views.index, name='index'),
    path('<int:tutorial_number>/', views.TN, name='TN'),
    path('', views.t, name='t'),
    path('detail/', views.detail, name='detail'),
    path('result/', views.result, name='result'),
    path('insert/', views.insert, name='insert'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('P/', include('P.urls')),
    path('NLP/', include('NLP.urls')),
    path('ML/', include('ML.urls')),
    path('',views.index)
]

myblog/NLP/models.py
from django.db import models

# Create your models here.

myblog/NLP/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
# Create your views here.


def index(request):
    template = loader.get_template('NLP/index.html')
    return HttpResponse(template.render({},request))
    # return HttpResponse('NLP')

def Tutorial(request):
    if request.method == 'POST':
        name = request.POST['filename'] # getting the name attribute from button
        try:
            template = loader.get_template(f'NLP/{name}.html')
        except Exception as error:
            print(error)
            return HttpResponse(f'Opps! We are sorry that the {name} tutorial is not available yet, but it will be out soon!')
        else:
            return HttpResponse(template.render({}, request))
    template = loader.get_template('NLP/index.html') # if no button is pressed, we go to index page of NLP
    return HttpResponse(template.render({'r':'Please choose a topic.'}, request))

myblog/NLP/templates/NLP/Word2vec.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Word2vec</title>
</head>
<body>
    <p>Word2vec Tutorial</p>

    <p>
        Word2vec is a word embedding technique. There are two different implementations of word2vec: continuous bag of words (CBOW) and skip gram.
        The CBOW algorithm uses the context words to predict the target word. On the other hand, the skip gram algorithm uses the target word to predict
        the context words. It is important to note that the skip gram algorithm is good for learning rare words while the CBOW algorithm is more suitable for
        small datasets.
    </p>
</body>
</html>

myblog/NLP/templates/NLP/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NLP</title>
</head>
<body>
    <p>Welcome to NLP.</p>
    {{r}}
    <form action="{% url 'NLP:Tutorial' %}" method="POST">
        {% csrf_token %}
        <button type="submit" name="filename" value="Word2vec">Word2vec</button>
        <button type="submit" name="filename" value="FastText">FastText</button>
        <button type="submit" name="filename" value="TF-IDF">TF-IDF</button>
    </form>
</body>
<link rel="stylesheet" type="text/css" href="{% static 'NLP/style.css' %}">
</html>